name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
          - goos: darwin
            goarch: 386

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binary
        run: |
          mkdir -p dist
          ext=""
          if [ "${{ matrix.goos }}" = "windows" ]; then ext=".exe"; fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/to64-${{ matrix.goos }}-${{ matrix.goarch }}${ext} ./cmd

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: to64-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Flatten artifact structure
        run: |
          mkdir flat
          find dist -type f -exec cp {} flat/ \;

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: flat/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
